language: node_js

node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g npm@6.9.0

services:
  - postgresql

addons:
  postgresql: "9"
  apt:
    packages:
    - postgresql-9
    - postgresql-client-9
env:
  global:
  - PGPORT=5433
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database teamwork;' -U postgres
  - npm run build
script:
  - npm test
after_success:
  - npm run coverage
