language: node_js

node_js:
  - 10.14.1 
cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g npm@6.9.0

install:
  - npm install
  - npm i @babel/core
services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database teamwork;' -U postgres
  - npm run build
script:
  - npm test
after_success:
  - npm run coverage
