language: node_js

node_js:
  - 10.14.1 
cache:
  directories:
    - "node_modules"
install:
  - npm install --ignore-scripts
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database teamwork;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD null;" -U postgres
  - npm run build
script:
  - npm test
after_success:
  - npm run coverage
