language: node_js

node_js:
  - 10.16.0 
cache:
  directories:
    - "node_modules"

services:
  - postgresql

env:
  global:
  - PGPORT=5433
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database teamwork;' -U postgres

script:
  - npm run test
  - npm run buid

after_success:
  - npm run coverage
