language: node_js

node_js:
  - 12.13.1 
cache:
  directories:
    - "node_modules"

services:
  - postgresql

env:
  global:
  - PGPORT=5432
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database abia_project;' -U postgres

script:
  - npm run test
  - npm run build

after_success:
  - npm run coverage
